In [1]:
import torch
torch.tensor([1.2, 3.4]).dtype

torch.float32

In [8]:
torch.set_default_dtype(torch.float64)
torch.tensor([1.2, 3.4]).dtype

torch.float64

In [13]:
a = torch.tensor([1.2,3.4])
print("a.dtype:",a.dtype)
print("a.dtype:",a.long().dtype)
print("a.dtype:",a.int().dtype)
print("a.dtype:",a.float().dtype)

a.dtype: torch.float64
a.dtype: torch.int64
a.dtype: torch.int32
a.dtype: torch.float32


In [14]:
torch.get_default_dtype()

torch.float64

### 生成张量

In [16]:
A = torch.tensor([[1.0, 1.0], [2,2]])
A

tensor([[1., 1.],
        [2., 2.]])

### 获取张量的维度

In [17]:
A.shape

torch.Size([2, 2])

### 获取张量的形状大小

In [18]:
A.size()

torch.Size([2, 2])

### 计算张量中包含元素的数量

In [19]:
A.numel()

4

In [60]:
B = torch.tensor((1,2,3),dtype=torch.float32,requires_grad=True)
B

tensor([1., 2., 3.], dtype=torch.float32, requires_grad=True)

In [70]:
y = B.pow(2).sum()
y.backward()
B.grad
# y

tensor([20., 40., 60.], dtype=torch.float32)

In [71]:
### 根据已有的数据创建张量
C = torch.Tensor([1,2,3,4])
C

tensor([1., 2., 3., 4.])

In [72]:
### 创建具有特定大小的张量
D = torch.Tensor(2,3)
D

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [73]:
torch.ones_like(D)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [74]:
torch.zeros_like(D)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [75]:
torch.rand_like(D)

tensor([[0.7337, 0.8800, 0.9802],
        [0.7560, 0.3319, 0.8066]])

In [80]:
E = [[1,2],[3,4]]
E = D.new_tensor(E)
print("D.dtype : ", D.dtype)
print("E.dtype : ", E.dtype)
D
# E

D.dtype :  torch.float64
E.dtype :  torch.float64


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [83]:
D.new_full((3,3), fill_value=1)
# D

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### 张量和NUmpy数据互相转换

In [88]:
## 利用Numpy 数组生成张量
import numpy as np

F = np.ones((3,3))
print(F)
## 使用torch.as_tensor()函数
Ftensor = torch.as_tensor(F)

print(Ftensor)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [89]:
## 使用torch.from_numpy()函数
Ftensor = torch.from_numpy(F)
Ftensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
### 使用张量的numpy()函数将张量转化为Numpy 数组
Ftensor.numpy()